import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const PRIMARY_COLOR = '#2e3091';
const SECONDARY_COLOR = '#3d3fa3';
const LIGHT_PRIMARY = '#eaebf7';
const ACCENT_COLOR = '#ff6b6b';
const BACKGROUND_COLOR = '#f5f7ff';
const WHITE = '#ffffff';
const DARK_TEXT = '#333333';
const LIGHT_TEXT = '#6c7293';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: BACKGROUND_COLOR,
  },
  card: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 5,
  },
  starIcon: {
    marginLeft: 5,
  },    
  image: {
    width: '100%',
    height: 180,
    borderRadius: 12,
  },
  cards: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 20,
    margin: 0,
    marginBottom: 16,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  dashboardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: LIGHT_PRIMARY,
    marginBottom: 16,
  },
  dashboardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  arrowIcon: {
    marginLeft: 10,
  },    
  meetupCard: {
    backgroundColor: LIGHT_PRIMARY,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: PRIMARY_COLOR,
  },
  meetupTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    marginBottom: 12,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  downArrowIcon: {
    alignSelf: 'center',
    marginVertical: 10,
  },  
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center', 
    justifyContent: 'space-between',
    marginBottom: 12,
  },    
  meetupInfo: {
    marginLeft: 8,
    marginRight: 16,
    color: LIGHT_TEXT,
    fontSize: 14,
  },
  locationText: {
    marginLeft: 8,
    color: LIGHT_TEXT,
    fontSize: 14,
    flex: 1,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginTop: 12,
    flexWrap: 'wrap',
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: WHITE,
    padding: 10,
    paddingHorizontal: 16,
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    marginRight: 12,
    marginBottom: 8,
  },
  declineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ACCENT_COLOR,
    padding: 10,
    borderRadius: 50,
    marginBottom: 8,
  },
  disabledButton: {
    backgroundColor: '#e0e0e0',
    opacity: 0.7,
  },
  buttonText: {
    color: PRIMARY_COLOR,
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '600',
  },
  buttonText1: {
    color: WHITE,
    fontSize: 14,
    fontWeight: '600',
  },
  disabledButton1: {
    backgroundColor: 'rgba(46, 48, 145, 0.5)', 
  },    
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  requirementCard: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  profileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileImage: {
    width: 46,
    height: 46,
    borderRadius: 23,
    marginRight: 12,
    borderWidth: 2,
    borderColor: LIGHT_PRIMARY,
  },
  profileName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  requirementContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  requirementText: {
    fontSize: 15,
    color: LIGHT_TEXT,
    marginBottom: 12,
    lineHeight: 22,
  },
  line: {
    display: 'none', 
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconStyle: {
    marginRight: 8,
  },
  header: {
    flexDirection: 'column',
    marginBottom: 16,
  },
  addButton: {
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignSelf: 'flex-end',
  },
  addButtonText: {
    color: WHITE,
    fontWeight: '600',
    fontSize: 14,
  },
  card: {
    backgroundColor: LIGHT_PRIMARY,
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    marginBottom: 20,
    borderLeftWidth: 3,
    borderLeftColor: PRIMARY_COLOR,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  requirementSection: {
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    position: 'relative',
  },
  rating: {
    fontSize: 14,
    color: LIGHT_TEXT,
    lineHeight: 22,
    marginTop: 8,
    fontStyle: 'italic',
  },
  acknowledgeButton: {
    position: 'absolute',
    top: -52,
    right: 0,
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  acknowledgeText: {
    color: WHITE,
    fontSize: 14,
    fontWeight: '600',
  },
  
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 16,
  },
  activeDot: {
    width: 8,
    height: 8,
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 4,
    marginHorizontal: 4,
  },
  inactiveDot: {
    width: 8,
    height: 8,
    backgroundColor: '#D8D8D8',
    borderRadius: 4,
    marginHorizontal: 4,
  },
  noMeetupCard: {
    padding: 24,
    backgroundColor: LIGHT_PRIMARY,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  noMeetupText: {
    fontSize: 16,
    color: LIGHT_TEXT,
    textAlign: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
    color: PRIMARY_COLOR,
  },
  buttonContainer: {
    flexDirection: 'row',  
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  home: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  addButton1: {
    backgroundColor: PRIMARY_COLOR,
    padding: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  addButton2: {
    backgroundColor: SECONDARY_COLOR,
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  disabledButtonText: {
    color: '#888',
  },
  rankingTable: {
    borderWidth: 1,
    borderColor: LIGHT_PRIMARY,
    borderRadius: 12,
    padding: 16,
    backgroundColor: WHITE,
  },
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: LIGHT_PRIMARY,
  },
  tableHeaderText: {
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    fontSize: 15,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  usernameText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 10,
    color: DARK_TEXT,
    flex: 1,
  },
  container1: {
    padding: 12,
    backgroundColor: LIGHT_PRIMARY,
    borderRadius: 12,
    marginTop: 8,
  },
  userContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    padding: 12,
    backgroundColor: WHITE,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  rankContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 5,
  },
  rankText: {
    marginRight: 10,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  nameText: {
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  amountText: {
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    textAlign: 'right', 
    width: 100,
  },
  dataContainer: {
    marginBottom: 12,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: LIGHT_PRIMARY,
  },
  note: {
    color: ACCENT_COLOR,
    fontSize: 13,
    margin: 8,
    fontStyle: 'italic',
    lineHeight: 18,
  },
  disabledText: {
    color: ACCENT_COLOR,
    fontSize: 14, 
    marginLeft: 8,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  modalContainer: {
    width: 320,
    padding: 24,
    backgroundColor: WHITE,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  modalText: {
    fontSize: 17,
    marginBottom: 24,
    textAlign: 'center',
    fontWeight: '600',
    color: DARK_TEXT,
    lineHeight: 24,
  },
  modalButton: {
    backgroundColor: PRIMARY_COLOR,
    padding: 12,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  modalButtonText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 24,
  },
  modalContainer1: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  modalContent: {
    width: "85%",
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  modalButtons: { 
    flexDirection: "row", 
    justifyContent: "space-around", 
    width: "100%",
    marginTop: 24,
  },
  modalButtonCancel: {
    backgroundColor: "#6c7293",
    padding: 12,
    borderRadius: 8,
    width: "42%",
    alignItems: "center",
  },
  modalButtonOK: {
    backgroundColor: PRIMARY_COLOR,
    padding: 12,
    borderRadius: 8,
    width: "42%",
    alignItems: "center",
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: LIGHT_PRIMARY,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  cardShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  infoLabel: {
    fontSize: 12,
    color: LIGHT_TEXT,
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 15,
    color: DARK_TEXT,
    fontWeight: '500',
  },
  badge: {
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  badgeText: {
    color: WHITE,
    fontSize: 12,
    fontWeight: '600',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: ACCENT_COLOR,
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  retryButtonText: {
    color: WHITE,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BACKGROUND_COLOR,
  },
  starContainer: {
    flexDirection: 'row',
    marginTop: 4,
  },
  
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 10,
  },
  refreshButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: LIGHT_PRIMARY,
  },
  refreshIcon: {
    marginRight: 5,
  },
  headerLeft: {
    flex: 1,
  },
});

export default styles;